### ISSUE TITLE
Items purchased by winning and losing teams over game time

### ISSUE THREAD

**Issue by o0oradaro0o** [GetDotaStats/site#110]

**Comment by o0oradaro0o** [comment]
Seeing what heroes are played by each side would also be very nice but i don't want to spam your issue button.  thanks again!

**Comment by jimmydorry** [comment]
Okay, I'll keep this in my to-do list.

**Comment by o0oradaro0o** [comment]
sorry i'm not sure if i was clear that I would want this data as like one of the charts that is a summery of all games, not just one game. 

Just like you show what heroes are most commonly used across all games it would be nice to have that broken down by which heroes were used by winners and losers. 

It would be good to have a similar breakdown for items purchased.
