### ISSUE TITLE
MMR

### ISSUE THREAD

**Issue by plzDontFucKMe** [GetDotaStats/site#113]
4 days ago my MMR updated , and now it does not. MMR sharing in game.

http://getdotastats.com/sig/46352657.png

**Comment by SinZ163** [comment]
Do you have LobbyExplorer installed and have MMR tracking enabled?

**Comment by jimmydorry** [comment]
I haven't heard anything more about this? Did you end up installing LX, and did your signature update after the 2hour caching time?

**Comment by jimmydorry** [comment]
There was a caching issue, which has now been fixed. Do a hard refresh of your signature, otherwise wait out the 2hours.

**Comment by plzDontFucKMe** [comment]
yes, I'm all set and it worked, but then ceased to be updated.
09.03.2015 15:07 пользователь "Trent Monahan" <notifications@github.com>
написал:

**Comment by jimmydorry** [comment]
Did you look at it since? It should have been all fixed 2days ago, just before my comment.

The last game you played was 3days ago, which is also the most recent date we have an MMR for (3967, 4065). The games and win-rate on your signature match Dotabuff.

Thanks for helping us test and fix this.

**Comment by plzDontFucKMe** [comment]
My last game was five days ago and my  MMP is not fully updated.

четверг, 12 марта 2015 г. пользователь jimmydorry написал:
> Did you look at it since? It should have been all fixed 2days ago, just
before my comment.
>
> The last game you played was 3days ago, which is also the most recent
date we have an MMR for (3967, 4065). The games and win-rate on your
signature match Dotabuff.
>
> Thanks for helping us test and fix this.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/knyUmL4kA4blaEj4bmP6a9TMDfxHCEGePN9luFFWrQbwV30r5O3XbtawS3csitNzfnP-yxbxM94OYs06LdWXSyXgPAf9JWHV5scNSJng1eCDRl4Lc70bT953zBwLNkb7pAQlfPvkAj6vNn5CdivgL4cV9KfsUg=s0-d-e1-ft#https://github.com/notifications/beacon/AKNBGU7xbYCpetTM0G4jg8lHTnGk9XdXks5n0NPegaJpZM4Drme-.gif
>

**Comment by jimmydorry** [comment]
Can you send a screenshot of what your MMR is meant to be, and perhaps play another game? The MMR is only updated every time the Dota2 client is opened and after a game has been played.

**Comment by jimmydorry** [comment]
No further response.
