### ISSUE TITLE
No plus window #NeedHelp

### ISSUE THREAD

**Issue by RomeoChicken** [GetDotaStats/site#119]
Hi i`ve got a problem. When a lobby starts i fail i mean no other window is opening its just staying in main dota window then i can reconnect over and over again and nothing... Help?
2 weeks ago it worked but now since i`ve reinstalled dota it won`t work...

**Comment by jimmydorry** [comment]
Do you have a wanky name? Source2 failed to join on bad names a few months ago.

Does source2 launch?

**Comment by jimmydorry** [comment]
This is also the wrong issue tracker. Remake the issue here: https://github.com/GetDotaStats/GetDotaLobby/issues

**Comment by jimmydorry** [comment]
Bump
