### ISSUE TITLE
Dota IMBA's item/ability icons

### ISSUE THREAD

**Issue by fcalife** [GetDotaStats/site#125]
Download at:

https://www.dropbox.com/s/zii6wi0ug5dwf55/DotaIMBA_images.rar?dl=0

**Comment by fcalife** [comment]
Download at:

https://www.dropbox.com/s/zii6wi0ug5dwf55/DotaIMBA_images.rar?dl=0

**Comment by jimmydorry** [comment]
Done. The system is still not properly implemented, so it relies on the spell/item name. If they are non-base then it will expect the matching icon (with same name), and if they use the base name then it will use the base icon.

http://getdotastats.com/#d2mods__match?id=3507b66e3bb384eff34b57c9bd56eb0a
