### ISSUE TITLE
Undefined index: winRateHeroes

### ISSUE THREAD

**Issue by or75** [GetDotaStats/site#134]
Why ? http://getdotastats.com/sig/241123295.png
db: http://ru.dotabuff.com/players/241123295

site:
http://i.imgur.com/OEPDjhm.png

wtf ???

**Comment by jimmydorry** [comment]
Thanks for reporting. I forgot to swap in the updated code to handle the DB layout update.

**Comment by jimmydorry** [comment]
And the image will be cached in your browser for 2hours since it was made. You will need to open it in a new tab, and hit CTRL + R
