### ISSUE TITLE
Developer Teams

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#141]
Multiple developers should have the power to see their private mod stats and manage the mod.

**Comment by jimmydorry** [comment]
The team members should only be allowed to see private mod details. The original assumption that only the main contributor can change files, is still valid.

**Comment by MNoya** [comment]
Can we un-nice-but-no-rush the part where non-owners aren't allowed to publish their mods? Footmen Frenzy's original owner is MIA and I would love to update it with statcollection so I can see if there's anyone still playing that :smile: Thanks in advance!

**Comment by jimmydorry** [comment]
Ok, lemme see what I can do in the next 30mins

**Comment by jimmydorry** [comment]
Done https://github.com/GetDotaStats/site/commit/3a013a84096c63a90d6f7d1b0b5d8097b66aa8ac https://github.com/GetDotaStats/site/commit/e69f1657207c475756869f946ee55009f52ef66b https://github.com/GetDotaStats/site/commit/29f3a6d7ca6ddf48970c17ba121c30607a1ab61c
