### ISSUE TITLE
phase custom listener error

### ISSUE THREAD

**Issue by SinZ163** [GetDotaStats/site#150]
Due to Lua weirdness, when I submit fragmented phase customs, skipped rounds in the message will be null (not sure what it looks like on your end), but it causes: ```Caught Exception: Missing `random` from Round `0` in Game array!```

Origin of error is at: https://github.com/GetDotaStats/site/blob/master/s2/api/s2_custom.php#L192
Message in console was:
```JSON
{"rounds":[null,{"players":[{"spell":-1,"steamID32":79037155,"score":0}],"game":{"random":0,"timer":1337,"predator":79037155}}],"schemaAuthKey":"[REDACTED]","modIdentifier":"[REDACTED]","schemaVersion":1,"matchID":545478,"authKey":"[REDACTED]"}
```

**Comment by jimmydorry** [comment]
Yep, definitely can't have null array placeholders.

I can filter those my end, but we will ultimately not want those submitted in the first place. For efficiency if nothing else.

**Comment by jimmydorry** [comment]
Also note, it will error if you are missing any schema fields in the round array with key=0, which is what the first array will always be unless you explicitly index them.

**Comment by SinZ163** [comment]
I'm not actually putting in null though, its valves shipped json library putting them in. Only solution I can see is to then make the keys strings, but that's just as bad potentially

**Comment by SinZ163** [comment]
string based keys actually was super effective

**Comment by jimmydorry** [comment]
It allows you to split the rounds into separate commits later too. :)
