### ISSUE TITLE
Mod Directory page

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#165]
Let's here what you want to see.

- [X] Super caching https://github.com/GetDotaStats/site/issues/168

**Comment by jimmydorry** [comment]
We need that caching.

https://github.com/GetDotaStats/site/issues/168

**Comment by K1llMan** [comment]
Allow to get stats by web requests from other sites or Panorama.

**Comment by SinZ163** [comment]
what would you use it for?

**Comment by jimmydorry** [comment]
Going to need more detail than that.

**Comment by K1llMan** [comment]
I'd like to show top playerы scoreboard on main game screen and same thing on site.

**Comment by jimmydorry** [comment]
Already mentioned in here. https://github.com/GetDotaStats/site/issues/162

Please make a new issue so it can be properly referred to. @SinZ163  reckons there is in-game support for basically showing a webpage, so we could make something very simple, very quickly.

**Comment by jimmydorry** [comment]
@mnoya Suggested we display more like the steamworkshop

**Comment by ynohtna92** [comment]
Total unique players, total players, and total hours please!
