### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#166]
Let's here what you want to see.

- [ ] Friend list
- [X] List recent matches played
- [X] power user flags (admin, mod, etc.)

**Comment by SinZ163** [comment]
Actually listing matches, and showing any flags on the account (GDS Admin, Mod of any games, VAC(?))

**Comment by jimmydorry** [comment]
Site power user flags (admin, mod, etc.)

**Comment by jimmydorry** [comment]
Friend list
