### ISSUE TITLE
Mod Game graphs inconsistency

### ISSUE THREAD

**Issue by MNoya** [GetDotaStats/site#210]
Phase 3 is black in SNS:

![img](http://puu.sh/l9rbU/43f173e628.png)

Phase 3 is green in Tohou:

![img](http://puu.sh/l9rcN/d05e9db67b.png)

I suggest Black (or Red), Blue, Green for Stage 1, 2 and 3 respectively.

**Comment by jimmydorry** [comment]
Simple fix will be to order them before throwing into graph. That should only take a minute or two.

I will need to look at the docs to see what the colour syntax is.

**Comment by jimmydorry** [comment]
Done
