### ISSUE TITLE
Make admin only variables on the site identifiable

### ISSUE THREAD

**Issue by SinZ163** [GetDotaStats/site#212]
ie, modders email on mod page or client IP on match page, and suggested colour is red.

Might be somewhat tricky considering its [currently an injected CPV](https://github.com/GetDotaStats/site/blob/master/site_files/s2/match.php#L236) but I believe in your PHP skills.

**Comment by jimmydorry** [comment]
EZPZ

**Comment by MNoya** [comment]
Ü
