### ISSUE TITLE
Make new favicon and flair

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#224]
Let's roll with totally intentional Dota logo as a % as a new flair concept and the favicon.

http://dota2.technology/images/getdotastats_flair.png

http://dota2.photography/images/getdotastats_logo_v3.png

**Comment by jimmydorry** [comment]
Noya's v1 http://imgur.com/KyQ8dE8

**Comment by MNoya** [comment]
v2 http://imgur.com/bkK43Xr

**Comment by jimmydorry** [comment]
It's live. Looks great. Nice job @MNoya !

http://dota2.solutions/images/favicons/favicon.ico

Want me to update the banner with the new gear style?
