### ISSUE TITLE
Show schema used on match page

### ISSUE THREAD

**Issue by SinZ163** [GetDotaStats/site#234]
Would assist Admins that aren't @jimmydorry to easily debug errors like `[CRON] [CMPV] Warning: Mod "Gladiator Arena Allstars (魔兽竞技场)" had values in the last report, but now does not! It may be broken! || http://getdotastats.com/s2/routine/log_hourly.html?1450450155` when you get matches still coming in like http://getdotastats.com/#s2__match?id=2944430

**Comment by jimmydorry** [comment]
Roger

**Comment by jimmydorry** [comment]
Pretty ugly, but it works. Gonna need to make the match summary bar nicer... some time in the future.
