### ISSUE TITLE
Query performance improvements

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#254]
- [x] CMG - Find lower matchID bound and copy all matches up into new table before working on them... instead of doing the filter straight. [code](https://github.com/GetDotaStats/site/blob/master/site_files/s2/routine/php/custom_match_gatherer.php#L101)
- [x] CMF - Update to use new method above
- [x] CMGV - Update to use new method above
- [x] CMPV - Update to use new method above
- [ ] Recent Games - Have separate match table with required data. Cron job that runs every five minutes. Cron job drops games older than a week from the table, and adds all of the games recorded with a matchID greater than the highest currently in the table.
- [ ] CMPV - Grab number of fields from schema. Process a max of 20k games (example). If it's more than max number of games, only process the first (20k * 10 [assume avg 10 custom fields] / 24 [actual number of fields]) = 8333 games. 
- [ ] CMPV - Find substitute for PHP data processing. Having it all in mysql operations will be a lot faster.

**Comment by jimmydorry** [comment]
CMF updated to new CMG method.

**Comment by jimmydorry** [comment]
CMGV and CMPV updated to new method.

**Comment by litianren001** [comment]
Would you please implement the winrate calculation asap? It's quite critical for me to balance my mod. Thanks so much! :smile:

**Comment by jimmydorry** [comment]
https://github.com/GetDotaStats/site/issues/280 <---- details finalised, and progress has been made... a whole new process queuing framework.
