### ISSUE TITLE
Show Rate % of Ended vs Loaded+Started

### ISSUE THREAD

**Issue by MNoya** [GetDotaStats/site#255]
I am checking the [load rate](https://github.com/Karawasa/Element-TD/issues/155#issuecomment-187709912) of the game every day to see if any of the performance updates are having an effect, it's easy to do the math on a calculator but would be nice if this info was displayed when hovering over a point on the graph (could be just to the right of the lobby number for each 1-2-3 line)

**Comment by jimmydorry** [comment]
Done

**Comment by MNoya** [comment]
Much appreciated
