### ISSUE TITLE
CSS not reading on Firefox

### ISSUE THREAD

**Issue by cowsforyou** [GetDotaStats/site#261]
Not sure if it's just my Firefox but it seems that the CSS is not being read. Site looks fine on my chrome. Here's a screenshot while browsing in FF: http://i.imgur.com/iPXgAWe.png

**Comment by jimmydorry** [comment]
Is there anything in your console log?

**Comment by cowsforyou** [comment]
@jimmydorry here's the console log: http://i.imgur.com/5Wy7WZQ.png I tried adding https://getdotastats.com/ to the security exceptions but to no avail.

**Comment by jimmydorry** [comment]
Try now. I'm guessing firefox doesn't follow the CSP specifications and decided on using their own directive names for different things.

**Comment by cowsforyou** [comment]
Fixed! All is well now. Thanks @jimmydorry
