### ISSUE TITLE
Website stuck on March 20th

### ISSUE THREAD

**Issue by cowsforyou** [GetDotaStats/site#270]
The site seems to be only collating games before March 20th. This is reflected on the graph on the individual games (eg https://getdotastats.com/#s2__mod?id=121) and the "week" game count on the mod directory page (https://getdotastats.com/#s2__directory) - the numbers are unusually small.

**Comment by jimmydorry** [comment]
Oops. When I rebooted the MySQL server forcefully, it blackholes the mod_matches temp table name. I forgot to change it after the last reboot.

You can see what happens when that cron (and others) runs here: https://getdotastats.com/s2/routine/log_10minute.html

**Comment by cowsforyou** [comment]
Thanks @jimmydorry !
