### ISSUE TITLE
Stats are down

### ISSUE THREAD

**Issue by MNoya** [GetDotaStats/site#277]
Day of crash was May 7

---

That said

![img](http://puu.sh/oMqIJ/4062aa2c9e.png)

32.222 games

**Comment by jimmydorry** [comment]
Fixed

**Comment by MNoya** [comment]
Thanks! 

Got any hopes of #274 this week or still busy as hell?

**Comment by jimmydorry** [comment]
Two assignments and a quiz due next week, as well as a few after-hours meetings. :(

It won't be #274 this week, but there will be a new task scheduler.

**Comment by MNoya** [comment]
Fair enough, good luck hve fun!
