### ISSUE TITLE
Breakdown of game modes/flags

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#55]
Pudge Wars interested in it, in particular

**Comment by MNoya** [comment]
Give [Warchasers](http://getdotastats.com/#d2mods__stats?id=10) stats breakdown for difficulty:

~~~
[modes] => Array
        (
            [difficulty] => 0
        )
~~~

difficulty takes values from 0 to 4

**Comment by jimmydorry** [comment]
Please ![BibleThump](http://dota2.photography/public/s/BibleThump.png)
