### ISSUE TITLE
Perry's API wishlist

### ISSUE THREAD

**Issue by Perryvw** [GetDotaStats/site#79]
I would like to be able to track stats for my mod on a dedicated website (ofcourse with some 'powered by getdotastats' stuff) For this I would ideally like getdotastats to provide me with the following things:

-Allow me to set a URL to which match details are sent once a new match is recorded
-A (RESTful) API allowing me to query user data for my mod (times played, achievements earned)

**Comment by jimmydorry** [comment]
Too resource intensive, and there is a lot of work setting this up to allow non-structured queries.

Specific enhancements should be suggested for creation or modification on the site.
