### ISSUE TITLE
Implement user_dota_stats

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#90]

**Comment by jimmydorry** [comment]
Lost the context. Nice issue reporting @SinZ163

**Comment by SinZ163** [comment]
wasn't this meant to be a webpage per user showing them their recent games, some graphs and other info like achievements and stuff

**Comment by jimmydorry** [comment]
Not sure. It has the naming convention of an API, and we already have an issue open for profile pages. https://github.com/GetDotaStats/site/issues/39
