### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by plzDontFucKMe** [GetDotaStats/site#95]
user does not exist or has not shared history

http://getdotastats.com/sig/46352657.png

A couple of days ago it worked, the history of my games open.

What is it?

**Comment by jimmydorry** [comment]
Thanks for bring this to my attention. Dotabuff has added a new rate-limit that we must fall a foul of.

I now catch that error.

I'll try getting in contact with them again, and see what we need to change.

**Comment by plzDontFucKMe** [comment]
Thank you very much for your help!

**Comment by jimmydorry** [comment]
We gucci now. The rate limit got lifted for us.
