### ISSUE TITLE
Hosting games

### ISSUE THREAD

**Issue by 090Gamer** [GetDotaStats/site#98]
Problem in hosting the game.
I do not see the window to create a local lobby.(The last one before the creation of Judging about presents in guide video)

**Comment by SinZ163** [comment]
You have the workshop tools installed, right?

**Comment by 090Gamer** [comment]
Yes I did everything according to the guide.
I can connect to custom games.
But I cant  create it.

I don't see this thing from guide:
![image](https://cloud.githubusercontent.com/assets/10743637/5940821/6e2a69ca-a737-11e4-9ecc-e74cb69b2be3.png)

**Comment by jimmydorry** [comment]
Moving this issue to the correct tracker.

**Comment by jimmydorry** [comment]
Look at it here: https://github.com/GetDotaStats/GetDotaLobby/issues/3
